### ISSUE TITLE
AADSTS50011: The reply url specified in the request does not match the reply urls configured for the application:

### ISSUE THREAD

**Issue by chanmmn** [microsoftgraph/msgraph-training-building-apps#12]
I have put my sharepoint url https://chanmm.sharepoint.com to the Redirect URLs. How to resolve this?
Thanks

**Comment by jasonjoh** [comment]
Closing this issue as we are archiving this repository and will not be maintaining it going forward. For an updated sample that covers these topics, please see:

- Console app: https://github.com/microsoftgraph/msgraph-training-dotnet-core
- JavaScript app: https://github.com/microsoftgraph/msgraph-training-javascriptspa
- Azure Function: https://github.com/microsoftgraph/msgraph-training-azurefunction-csharp
- Xamarin app: https://github.com/microsoftgraph/msgraph-training-xamarin

We apologize for any inconvenience.
