### ISSUE TITLE
Step 4 missing something

### ISSUE THREAD

**Issue by krisrajzlive** [microsoftgraph/msgraph-training-building-apps#14]
Looks like step 4 is missing something as I do not see any such like  urn:ietf:wg:oauth:2.0:oob .

**Comment by jasonjoh** [comment]
Closing this issue as we are archiving this repository and will not be maintaining it going forward. For an updated sample that covers these topics, please see:

- Console app: https://github.com/microsoftgraph/msgraph-training-dotnet-core
- JavaScript app: https://github.com/microsoftgraph/msgraph-training-javascriptspa
- Azure Function: https://github.com/microsoftgraph/msgraph-training-azurefunction-csharp
- Xamarin app: https://github.com/microsoftgraph/msgraph-training-xamarin

We apologize for any inconvenience.
